---
- name: "Verificar que openssh-server está instalado"
  ansible.builtin.apt:
    cache_valid_time: 3600
    name: "openssh-server"
    state: "present"
    update_cache: true

- name: "Configurar el puerto"
  ansible.builtin.lineinfile:
    path: "/etc/ssh/sshd_config"
    search_string: "Port"
    line: "Port {{ ssh_puerto }}"

- name: "Crear el directorio de configuración para el administrador"
  ansible.builtin.file:
    group: "{{ ssh_admin }}"
    mode: 0700
    path: "/home/{{ ssh_admin }}/.ssh"
    owner: "{{ ssh_admin }}"
    state: "directory"

- name: "Agregar las llaves al administrador"
  ansible.builtin.lineinfile:
    create: true
    group: "{{ ssh_admin }}"
    path: "/home/{{ ssh_admin }}/.ssh/authorized_keys"
    search_string: "{{ item }}"
    line: "{{ item }}"
    owner: "{{ ssh_admin }}"
    mode: 0600
  loop: "{{ ssh_llaves_admin }}"
